name: Run .NET Project Migration Tool
description: Use este modelo para acionar o processo de migração do seu projeto .NET com nossa ferramenta automatizada.
title: Run .NET Project Migration Tool
labels:
  - stackspot
  - migration-net-tool
body:
  - type: markdown
    attributes:
      value: |
        Preencha os campos abaixo para disparar o workflow de migração.
  - type: markdown
    attributes:
      value: |
        **.NET Version:** `net8` 
  - type: input
    id: git_url
    attributes:
      label: Repositório
      description: URL do repositório Git.
      placeholder: "https://github.com/your-repo/your-project.git"
  - type: input
    id: branch
    attributes:
      label: Branch
      description: Branch do repositório.
      placeholder: "main"
