name: Run dotnet 8 Migration
description: Use this template to trigger the Migration Workflow.
title: Run dotnet 8 Migration
body:
  - type: markdown
    attributes:
      value: |
        Preencha os campos abaixo para disparar o workflow de migração.
  - type: markdown
    attributes:
      value: |
        **.NET Version:** `net8`  
        *(Este campo é fixo e não pode ser alterado.)*
  - type: input
    id: git_url
    attributes:
      label: Git Repository URL
      description: URL do repositório Git.
      placeholder: "https://github.com/your-repo/your-project.git"
  - type: input
    id: branch
    attributes:
      label: Git Branch
      description: Branch do repositório Git.
      placeholder: "main"
