name: Migration Workflow

on:
  workflow_dispatch:
    inputs:
      dotnetVersion:
        description: '.NET Version'
        required: true
      gitUrl:
        description: 'Git Repository URL'
        required: true
      pat:
        description: 'Git Personal Access Token'
        required: true        
      branch:
        description: 'Git Branch'
        required: true

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git User
        run: |
          git config --global user.name ".NET Project Migration Tool"
          git config --global user.email "stackspot@stackspot.com"        

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
              
      - name: Run Action Stackspot
        uses: stack-spot/cli-github-action-run-command@v1.0.0
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_key: ${{ secrets.CLIENT_KEY }}
          realm: ${{ secrets.REALM }}
          command_stk: |
            run action pid/dotnet-migrator \
              --dotnet_version ${{ github.event.inputs.dotnetVersion }} \
              --git_url ${{ github.event.inputs.gitUrl }} \
              --git_token ${{ github.event.inputs.pat }} \
              --git_branch ${{ github.event.inputs.branch }}
